### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by RichardLitt** [cagross/react-specials#1]
There's no license file! Have you considered the MIT license?

**Comment by cagross** [comment]
Hey thanks for this.  I didn't see that you created this issue.  Any idea why GitHub doesn't notify me when someone creates a new issue?  If not no problem--I can look into that.

> There's no license file! Have you considered the MIT license?

OK let's chat about this.  For now I have intentionally omitted the license, and here was my rationale.  I'm open to discussing that decision.  For now, the app is not ready for any kind of public use or release.  If anything, it is in its pre-release phase (i.e. version below 1.0.0).  The repo exists mainly to show off the app/code to potential employers and friends--not so much to solicit collaboration/contribution.  In fact, for now, I'd prefer to be the only one working on it.  So in light of that, [the GitHub license page](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository) says that if I do not specify a license in my repo, then no one can copy or use my work.  That seemed to be along the lines of what I want for now, so that's what I did.

In the future though (probably if/when version 1.0.0 of the app is ever released), I will be happy to have contributions.  At that time, [this page](https://choosealicense.com/) (which I believe is run by GitHub) says a typical course of action is to use the same license used by the main technology used by my app.  In my case that is ReactJS, and they use the MIT license.

What are your thoughts on that course of action?

**Comment by RichardLitt** [comment]
Here's an interesting counter question for you: 

>  So in light of that, the GitHub license page says that if I do not specify a license in my repo, then no one can copy or use my work. That seemed to be along the lines of what I want for now, so that's what I did.

Why should I help you, if you won't help others?

**Comment by cagross** [comment]
OK interesting outlook--one I admittedly had not considered.  I want to start by saying I definitely can be convinced to give it the MIT license now.  But before I do: is it customary to open a project up to collaboration in the pre-release stages?  That's not just me trying to win this argument.  This is my first ever project, so I kind of thought from an organizational point of view, that it might be advantageous for me to limit collaborators for now.  The main reasons were:

1. It will keep things simpler for me.
2. The app is not in any way a finished product.  At this point, I may throw away many parts of the code base and start over.  

Let me know what you think about those two reasons.  Do they have merit?  Or am I overestimating them?  If you think the latter, then I'll go ahead and add the MIT license now.

Thanks!

**Comment by RichardLitt** [comment]
I think that some of the resources here may help you: https://opensource.guide/

The odds of someone helping are low, but making connections is always better than making something that isn't used. I think you're overestimating the possibility of someone making your life more difficult. If anything, it'll make it better.

**Comment by cagross** [comment]
OK understood on your comments, and I'll have a read through the Open Source Guide--thanks for that.  I'll add the MIT license.  If I recall, I'll have to add it to both the repo and separately, the README.  It may require a day or two though, as things have picked up work-wise.  When I do so, I'll update here.
